name: combined-changelog
on:
  workflow_dispatch:        # manual run
  schedule:
    - cron: "0 */12 * * *"  # twice a day UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Check out this repo first to get the workspace
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Check out both source repos (full history)
      - uses: actions/checkout@v4
        with:
          repository: mhmdez/studibudi
          path: studibudi
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/checkout@v4
        with:
          repository: mhmdez/studi-budi-ai-tutor
          path: studi-budi-ai-tutor
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      # Debug: Check what we've got
      - name: Debug repository structure
        run: |
          echo "=== Current directory ==="
          pwd
          ls -la
          echo "=== Studibudi directory ==="
          ls -la studibudi
          cd studibudi && git log --oneline -5
          cd ..
          echo "=== Studi-budi-ai-tutor directory ==="
          ls -la studi-budi-ai-tutor
          cd studi-budi-ai-tutor && git log --oneline -5
          cd ..

      # Run git-cliff over both histories
      - uses: orhun/git-cliff-action@v2
        with:
          config: cliff.toml
          args: >
            --repository studibudi
            --repository studi-budi-ai-tutor
            --output CHANGELOG.md
            --verbose

      # Debug: Check the generated changelog
      - name: Debug generated changelog
        run: |
          echo "=== Generated CHANGELOG.md ==="
          cat CHANGELOG.md

      # Commit only if CHANGELOG.md changed
      - name: Commit changes
        run: |
          git config user.name  "cliff-bot"
          git config user.email "bot@users.noreply.github.com"
          
          if ! git diff --quiet CHANGELOG.md; then
            git add CHANGELOG.md
            git commit -m "auto: update combined changelog"
            git push
          else
            echo "No changes to CHANGELOG.md"
          fi
